#!/bin/bash

# Door Log process started - Write today's date to log files
# Using -printf- command to print line break to highlight reboot in log 
#   - Alternatively, you can uncomment the following two lines to start new logs on every reboot

# rm /usr/share/webiopi/htdocs/door.log
# rm /var/log/door.log

# printf "\nDoor Tracker started at " >> /var/log/door.log
# date >> /var/log/door.log

printf "\nDoor Tracker started at " >> /usr/share/webiopi/htdocs/door.log
date >> /usr/share/webiopi/htdocs/door.log

# GPIO 18 is used as the door sensor. Must be changed in two places if different (Lines 17 & 26)
echo "18" > /sys/class/gpio/export

# Loop this whole script
while true

do
# Assign the previous value (stored in file /usr/bin/garage_state) & get the current status of GPIO pin
# Make sure to update GPIO value to the door sensor
STATE_PRV=$(</usr/bin/door_state)
STATE_CUR=$(</sys/class/gpio/gpio18/value)

# ====================================
# STATE_TEXT = 1 > open
# STATE_TEXT = 0 > closed

if [ $STATE_CUR = 1 ]
then
       STATE_TEXT='OPEN'
else
       STATE_TEXT='CLOSED'
fi

# ====================================
if [ "$STATE_PRV" = "$STATE_CUR" ]
then
       sleep 5
else
       date >> /var/log/door.log
       echo "Door Tracker " $STATE_CUR >> /var/log/door.log
       echo " 1=Open, 0=Closed" >> /var/log/door.log

       STR1=$(date +%F)" "$(date +%R)
       echo $STR1 "Door is" $STATE_TEXT >> /usr/share/webiopi/htdocs/door.log

       echo $STATE_CUR > /usr/bin/door_state
fi
       date

done
